SET
REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE `comment`;
TRUNCATE TABLE `course`;
TRUNCATE TABLE `major`;
TRUNCATE TABLE `post`;
TRUNCATE TABLE `profile`;
TRUNCATE TABLE `user`;

SET
REFERENTIAL_INTEGRITY TRUE