SET REFERENTIAL_INTEGRITY FALSE;

TRUNCATE TABLE comment;
TRUNCATE TABLE course;
TRUNCATE TABLE major;
TRUNCATE TABLE post;
TRUNCATE TABLE profile;
TRUNCATE TABLE user;
truncate table user_role;

SET
REFERENTIAL_INTEGRITY TRUE