name: Code Coverage

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches:
      - 'main'

permissions:
  contents: read

jobs:
  code-coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'oracle'


      # Gradle 설정
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/dev' }}

        # gradlew 파일 권한 지정
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: test
        run: ./gradlew test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        if: always()
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/jacoco
          fail_ci_if_error: true
        continue-on-error: true